#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD07AUN import recorddefs


structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 1, MAX: 1},
    {ID: 'DTM', MIN: 1, MAX: 10},
    {ID: 'IMD', MIN: 0, MAX: 10},
    {ID: 'MEA', MIN: 0, MAX: 10},
    {ID: 'FTX', MIN: 0, MAX: 5},
    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 2},
    ]},
    {ID: 'NAD', MIN: 0, MAX: 10, LEVEL: [
        {ID: 'LOC', MIN: 0, MAX: 5},
        {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 2},
        ]},
        {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
            {ID: 'COM', MIN: 0, MAX: 5},
        ]},
    ]},
    {ID: 'LIN', MIN: 0, MAX: 200, LEVEL: [
        {ID: 'PIA', MIN: 0, MAX: 10},
        {ID: 'IMD', MIN: 0, MAX: 10},
        {ID: 'MEA', MIN: 0, MAX: 10},
        {ID: 'PSD', MIN: 0, MAX: 1},
        {ID: 'SPS', MIN: 0, MAX: 1},
        {ID: 'DTM', MIN: 0, MAX: 10},
        {ID: 'QTY', MIN: 0, MAX: 99},
        {ID: 'FTX', MIN: 0, MAX: 5},
        {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 2},
        ]},
        {ID: 'NAD', MIN: 0, MAX: 10, LEVEL: [
            {ID: 'LOC', MIN: 0, MAX: 5},
            {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 2},
            ]},
            {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 5},
            ]},
        ]},
        {ID: 'TEM', MIN: 0, MAX: 100, LEVEL: [
            {ID: 'MEA', MIN: 0, MAX: 100},
            {ID: 'DTM', MIN: 0, MAX: 10},
            {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 2},
            ]},
        ]},
        {ID: 'CCI', MIN: 0, MAX: 200, LEVEL: [
            {ID: 'PSD', MIN: 0, MAX: 10},
            {ID: 'SPS', MIN: 0, MAX: 10},
            {ID: 'DTM', MIN: 0, MAX: 10},
            {ID: 'FTX', MIN: 0, MAX: 10},
            {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 2},
            ]},
            {ID: 'MEA', MIN: 0, MAX: 999, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 10},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 2},
                ]},
            ]},
            {ID: 'STA', MIN: 0, MAX: 100, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 10},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 2},
                ]},
            ]},
            {ID: 'TEM', MIN: 0, MAX: 100, LEVEL: [
                {ID: 'MEA', MIN: 0, MAX: 100},
                {ID: 'DTM', MIN: 0, MAX: 10},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 2},
                ]},
            ]},
        ]},
        {ID: 'GIN', MIN: 0, MAX: 100, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 10},
            {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 2},
            ]},
            {ID: 'CCI', MIN: 0, MAX: 200, LEVEL: [
                {ID: 'PSD', MIN: 0, MAX: 10},
                {ID: 'SPS', MIN: 0, MAX: 10},
                {ID: 'DTM', MIN: 0, MAX: 10},
                {ID: 'FTX', MIN: 0, MAX: 10},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 2},
                ]},
                {ID: 'MEA', MIN: 0, MAX: 999, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 10},
                    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 2},
                    ]},
                ]},
                {ID: 'STA', MIN: 0, MAX: 100, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 10},
                    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 2},
                    ]},
                ]},
                {ID: 'TEM', MIN: 0, MAX: 100, LEVEL: [
                    {ID: 'MEA', MIN: 0, MAX: 100},
                    {ID: 'DTM', MIN: 0, MAX: 10},
                    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 2},
                    ]},
                ]},
            ]},
        ]},
        {ID: 'PRC', MIN: 0, MAX: 100, LEVEL: [
            {ID: 'NAD', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'LOC', MIN: 0, MAX: 5},
            ]},
            {ID: 'CCI', MIN: 0, MAX: 200, LEVEL: [
                {ID: 'PSD', MIN: 0, MAX: 10},
                {ID: 'SPS', MIN: 0, MAX: 10},
                {ID: 'DTM', MIN: 0, MAX: 10},
                {ID: 'FTX', MIN: 0, MAX: 10},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 2},
                ]},
                {ID: 'MEA', MIN: 0, MAX: 999, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 10},
                    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 2},
                    ]},
                ]},
                {ID: 'STA', MIN: 0, MAX: 100, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 10},
                    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 2},
                    ]},
                ]},
                {ID: 'TEM', MIN: 0, MAX: 100, LEVEL: [
                    {ID: 'MEA', MIN: 0, MAX: 100},
                    {ID: 'DTM', MIN: 0, MAX: 10},
                    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 2},
                    ]},
                ]},
            ]},
        ]},
    ]},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
