#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD09AUN import recorddefs


structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 1, MAX: 1},
    {ID: 'DTM', MIN: 1, MAX: 5},
    {ID: 'MKS', MIN: 0, MAX: 1},
    {ID: 'RFF', MIN: 0, MAX: 9, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 9},
    ]},
    {ID: 'NAD', MIN: 1, MAX: 5, LEVEL: [
        {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
            {ID: 'COM', MIN: 0, MAX: 5},
        ]},
        {ID: 'RFF', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 9},
        ]},
    ]},
    {ID: 'CUX', MIN: 0, MAX: 5, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 5},
        {ID: 'STS', MIN: 0, MAX: 5},
    ]},
    {ID: 'LOC', MIN: 0, MAX: 200000, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 5},
        {ID: 'FTX', MIN: 0, MAX: 5},
        {ID: 'RFF', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 5},
        ]},
        {ID: 'LIN', MIN: 0, MAX: 200000, LEVEL: [
            {ID: 'PIA', MIN: 0, MAX: 5},
            {ID: 'IMD', MIN: 0, MAX: 5},
            {ID: 'DTM', MIN: 0, MAX: 9},
            {ID: 'PAC', MIN: 0, MAX: 5},
            {ID: 'RFF', MIN: 0, MAX: 5},
            {ID: 'DOC', MIN: 0, MAX: 5},
            {ID: 'ALI', MIN: 0, MAX: 5},
            {ID: 'MOA', MIN: 0, MAX: 5},
            {ID: 'GIN', MIN: 0, MAX: 9999},
            {ID: 'PRI', MIN: 0, MAX: 999, LEVEL: [
                {ID: 'CUX', MIN: 0, MAX: 1},
            ]},
            {ID: 'PAI', MIN: 0, MAX: 9},
            {ID: 'QTY', MIN: 0, MAX: 999, LEVEL: [
                {ID: 'MKS', MIN: 0, MAX: 1},
                {ID: 'NAD', MIN: 0, MAX: 1},
                {ID: 'PRI', MIN: 0, MAX: 9},
                {ID: 'DTM', MIN: 0, MAX: 9},
                {ID: 'RFF', MIN: 0, MAX: 9},
                {ID: 'STS', MIN: 0, MAX: 9},
            ]},
        ]},
    ]},
    {ID: 'GEI', MIN: 0, MAX: 1, LEVEL: [
        {ID: 'LIN', MIN: 0, MAX: 999999, LEVEL: [
            {ID: 'PIA', MIN: 0, MAX: 99},
            {ID: 'IMD', MIN: 0, MAX: 9},
            {ID: 'PAC', MIN: 0, MAX: 9},
            {ID: 'MOA', MIN: 0, MAX: 9},
            {ID: 'LOC', MIN: 0, MAX: 9999, LEVEL: [
                {ID: 'RFF', MIN: 0, MAX: 9},
                {ID: 'DTM', MIN: 0, MAX: 9},
                {ID: 'MOA', MIN: 0, MAX: 9},
                {ID: 'QTY', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'PRI', MIN: 0, MAX: 9},
                    {ID: 'DTM', MIN: 0, MAX: 9},
                    {ID: 'RFF', MIN: 0, MAX: 9},
                    {ID: 'STS', MIN: 0, MAX: 9},
                ]},
            ]},
        ]},
    ]},
    {ID: 'UNS', MIN: 1, MAX: 1},
    {ID: 'MOA', MIN: 0, MAX: 9},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
