#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD99BUN import recorddefs


structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 1, MAX: 1},
    {ID: 'DTM', MIN: 1, MAX: 5},
    {ID: 'IRQ', MIN: 0, MAX: 1},
    {ID: 'FTX', MIN: 0, MAX: 20},
    {ID: 'NAD', MIN: 1, MAX: 25, LEVEL: [
        {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
            {ID: 'COM', MIN: 0, MAX: 5},
        ]},
    ]},
    {ID: 'DOC', MIN: 0, MAX: 999, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 5},
        {ID: 'LIN', MIN: 0, MAX: 200000, LEVEL: [
            {ID: 'PIA', MIN: 0, MAX: 25},
            {ID: 'IMD', MIN: 0, MAX: 10},
            {ID: 'MEA', MIN: 0, MAX: 5},
            {ID: 'STS', MIN: 0, MAX: 9},
            {ID: 'RFF', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 1},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 5},
                {ID: 'QTY', MIN: 0, MAX: 1},
            ]},
        ]},
    ]},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
