#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD95AUN import recorddefs


structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 1, MAX: 1},
    {ID: 'DTM', MIN: 1, MAX: 10},
    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 1},
    ]},
    {ID: 'NAD', MIN: 0, MAX: 20, LEVEL: [
        {ID: 'LOC', MIN: 0, MAX: 10},
        {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
            {ID: 'COM', MIN: 0, MAX: 5},
        ]},
    ]},
    {ID: 'UNS', MIN: 1, MAX: 1},
    {ID: 'NAD', MIN: 0, MAX: 500, LEVEL: [
        {ID: 'LOC', MIN: 0, MAX: 10},
        {ID: 'FTX', MIN: 0, MAX: 5},
        {ID: 'DOC', MIN: 0, MAX: 10, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 10},
        ]},
        {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
            {ID: 'COM', MIN: 0, MAX: 5},
        ]},
        {ID: 'TDT', MIN: 0, MAX: 10, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 5},
        ]},
        {ID: 'LIN', MIN: 0, MAX: 9999, LEVEL: [
            {ID: 'PIA', MIN: 0, MAX: 10},
            {ID: 'IMD', MIN: 0, MAX: 10},
            {ID: 'MEA', MIN: 0, MAX: 5},
            {ID: 'ALI', MIN: 0, MAX: 5},
            {ID: 'GIN', MIN: 0, MAX: 100},
            {ID: 'GIR', MIN: 0, MAX: 100},
            {ID: 'LOC', MIN: 0, MAX: 100},
            {ID: 'DTM', MIN: 0, MAX: 5},
            {ID: 'FTX', MIN: 0, MAX: 5},
            {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 5},
            ]},
            {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 1},
            ]},
            {ID: 'TDT', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 5},
            ]},
            {ID: 'QTY', MIN: 0, MAX: 200, LEVEL: [
                {ID: 'SCC', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 2},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 1},
                ]},
            ]},
            {ID: 'PAC', MIN: 0, MAX: 50, LEVEL: [
                {ID: 'MEA', MIN: 0, MAX: 10},
                {ID: 'QTY', MIN: 0, MAX: 5},
                {ID: 'DTM', MIN: 0, MAX: 5},
                {ID: 'PCI', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'GIN', MIN: 0, MAX: 10},
                ]},
                {ID: 'QVR', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 5},
                    {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 1},
                    ]},
                ]},
            ]},
        ]},
    ]},
    {ID: 'LIN', MIN: 0, MAX: 9999, LEVEL: [
        {ID: 'PIA', MIN: 0, MAX: 10},
        {ID: 'IMD', MIN: 0, MAX: 10},
        {ID: 'MEA', MIN: 0, MAX: 5},
        {ID: 'ALI', MIN: 0, MAX: 5},
        {ID: 'GIN', MIN: 0, MAX: 100},
        {ID: 'GIR', MIN: 0, MAX: 100},
        {ID: 'DTM', MIN: 0, MAX: 5},
        {ID: 'FTX', MIN: 0, MAX: 5},
        {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 1},
        ]},
        {ID: 'QTY', MIN: 0, MAX: 50, LEVEL: [
            {ID: 'SCC', MIN: 0, MAX: 1},
            {ID: 'DTM', MIN: 0, MAX: 2},
            {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 1},
            ]},
        ]},
        {ID: 'PAC', MIN: 0, MAX: 10, LEVEL: [
            {ID: 'MEA', MIN: 0, MAX: 10},
            {ID: 'QTY', MIN: 0, MAX: 5},
            {ID: 'DTM', MIN: 0, MAX: 5},
            {ID: 'PCI', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'GIN', MIN: 0, MAX: 10},
            ]},
        ]},
        {ID: 'NAD', MIN: 0, MAX: 500, LEVEL: [
            {ID: 'LOC', MIN: 0, MAX: 10},
            {ID: 'FTX', MIN: 0, MAX: 5},
            {ID: 'DOC', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 1},
            ]},
            {ID: 'CTA', MIN: 0, MAX: 5, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 5},
            ]},
            {ID: 'QTY', MIN: 0, MAX: 50, LEVEL: [
                {ID: 'SCC', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 2},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 1},
                ]},
            ]},
            {ID: 'QVR', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 5},
                {ID: 'RFF', MIN: 0, MAX: 10, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 1},
                ]},
            ]},
            {ID: 'TDT', MIN: 0, MAX: 10, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 5},
            ]},
        ]},
    ]},
    {ID: 'UNS', MIN: 1, MAX: 1},
    {ID: 'CNT', MIN: 0, MAX: 5},
    {ID: 'FTX', MIN: 0, MAX: 5},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
