#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD11BUN import recorddefs


structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 1, MAX: 1},
    {ID: 'DTM', MIN: 0, MAX: 9},
    {ID: 'MOA', MIN: 0, MAX: 1},
    {ID: 'IFD', MIN: 0, MAX: 9},
    {ID: 'RFF', MIN: 0, MAX: 99999},
    {ID: 'CUX', MIN: 0, MAX: 9},
    {ID: 'FII', MIN: 0, MAX: 1},
    {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 9},
        {ID: 'GEI', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'PYT', MIN: 0, MAX: 99},
        ]},
    ]},
    {ID: 'GOR', MIN: 0, MAX: 9, LEVEL: [
        {ID: 'LOC', MIN: 0, MAX: 1},
        {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'COM', MIN: 0, MAX: 9},
        ]},
    ]},
    {ID: 'STS', MIN: 0, MAX: 9, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 99},
        {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'ELU', MIN: 0, MAX: 99},
        ]},
    ]},
    {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 9},
        {ID: 'GEI', MIN: 0, MAX: 1},
        {ID: 'STS', MIN: 0, MAX: 1},
        {ID: 'IFD', MIN: 0, MAX: 9},
        {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'COM', MIN: 0, MAX: 9},
        ]},
    ]},
    {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
        {ID: 'RFF', MIN: 0, MAX: 9},
        {ID: 'DTM', MIN: 0, MAX: 9},
        {ID: 'MOA', MIN: 0, MAX: 9},
        {ID: 'ALI', MIN: 0, MAX: 1},
        {ID: 'QTY', MIN: 0, MAX: 99},
        {ID: 'TSR', MIN: 0, MAX: 99},
        {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'IFD', MIN: 0, MAX: 1},
            {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 9},
            ]},
        ]},
        {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 99},
        ]},
    ]},
    {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
        {ID: 'FTX', MIN: 0, MAX: 9},
        {ID: 'DTM', MIN: 0, MAX: 9},
        {ID: 'GEI', MIN: 0, MAX: 1},
        {ID: 'ALI', MIN: 0, MAX: 9},
        {ID: 'ERP', MIN: 0, MAX: 999, LEVEL: [
            {ID: 'ELU', MIN: 0, MAX: 99},
        ]},
    ]},
    {ID: 'AJT', MIN: 0, MAX: 99, LEVEL: [
        {ID: 'ERP', MIN: 0, MAX: 999, LEVEL: [
            {ID: 'ELU', MIN: 0, MAX: 99},
        ]},
    ]},
    {ID: 'ERC', MIN: 0, MAX: 99, LEVEL: [
        {ID: 'ERP', MIN: 0, MAX: 999, LEVEL: [
            {ID: 'ELU', MIN: 0, MAX: 99},
        ]},
    ]},
    {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 9},
        {ID: 'LOC', MIN: 0, MAX: 9},
        {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
            {ID: 'IFD', MIN: 0, MAX: 1},
            {ID: 'DTM', MIN: 0, MAX: 9},
            {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 9},
            ]},
        ]},
    ]},
    {ID: 'GIR', MIN: 0, MAX: 9, LEVEL: [
        {ID: 'LOC', MIN: 0, MAX: 99},
        {ID: 'VLI', MIN: 0, MAX: 1},
        {ID: 'DTM', MIN: 0, MAX: 99},
        {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'IFD', MIN: 0, MAX: 1},
            {ID: 'DTM', MIN: 0, MAX: 9},
            {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 9},
            ]},
        ]},
    ]},
    {ID: 'TAX', MIN: 0, MAX: 99, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 9},
        {ID: 'ALI', MIN: 0, MAX: 9},
        {ID: 'MOA', MIN: 0, MAX: 99},
        {ID: 'QTY', MIN: 0, MAX: 99},
        {ID: 'PAI', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'RFF', MIN: 0, MAX: 99},
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'GIR', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'LOC', MIN: 0, MAX: 99},
                {ID: 'VLI', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 9},
                    {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 9},
                    ]},
                ]},
            ]},
        ]},
    ]},
    {ID: 'PAC', MIN: 0, MAX: 99999, LEVEL: [
        {ID: 'SEQ', MIN: 1, MAX: 1},
        {ID: 'PCI', MIN: 0, MAX: 99},
        {ID: 'FTX', MIN: 0, MAX: 1},
        {ID: 'GEI', MIN: 0, MAX: 1},
        {ID: 'DIM', MIN: 0, MAX: 1},
        {ID: 'MEA', MIN: 0, MAX: 1},
    ]},
    {ID: 'TMP', MIN: 0, MAX: 9, LEVEL: [
        {ID: 'MEA', MIN: 0, MAX: 1},
        {ID: 'DGS', MIN: 0, MAX: 1},
    ]},
    {ID: 'TDT', MIN: 0, MAX: 9, LEVEL: [
        {ID: 'DTM', MIN: 0, MAX: 99},
        {ID: 'RFF', MIN: 0, MAX: 99},
        {ID: 'QTY', MIN: 0, MAX: 99},
        {ID: 'MEA', MIN: 0, MAX: 99},
        {ID: 'MOA', MIN: 0, MAX: 99},
        {ID: 'POC', MIN: 0, MAX: 99},
        {ID: 'DIM', MIN: 0, MAX: 99},
        {ID: 'FTX', MIN: 0, MAX: 99},
        {ID: 'GDS', MIN: 0, MAX: 99},
        {ID: 'STS', MIN: 0, MAX: 1},
        {ID: 'GPO', MIN: 0, MAX: 1},
        {ID: 'SEQ', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'FTX', MIN: 1, MAX: 1},
        ]},
        {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'SEQ', MIN: 1, MAX: 1},
            {ID: 'DTM', MIN: 0, MAX: 99},
        ]},
        {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'IFD', MIN: 0, MAX: 1},
            {ID: 'NAT', MIN: 0, MAX: 1},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'LOC', MIN: 0, MAX: 99},
            {ID: 'EMP', MIN: 0, MAX: 99},
            {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 99},
            ]},
            {ID: 'ADR', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'EMP', MIN: 0, MAX: 1},
            ]},
        ]},
        {ID: 'EQD', MIN: 0, MAX: 9999, LEVEL: [
            {ID: 'SEQ', MIN: 1, MAX: 1},
            {ID: 'QTY', MIN: 0, MAX: 1},
            {ID: 'GEI', MIN: 0, MAX: 99},
            {ID: 'SEL', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
            ]},
            {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
        ]},
    ]},
    {ID: 'UNS', MIN: 1, MAX: 1},
    {ID: 'SEQ', MIN: 0, MAX: 9999, LEVEL: [
        {ID: 'ALI', MIN: 0, MAX: 99},
        {ID: 'IFD', MIN: 0, MAX: 99},
        {ID: 'DTM', MIN: 0, MAX: 99},
        {ID: 'RFF', MIN: 0, MAX: 99},
        {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'IFD', MIN: 0, MAX: 1},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 99},
        ]},
        {ID: 'DOC', MIN: 0, MAX: 999, LEVEL: [
            {ID: 'SEQ', MIN: 1, MAX: 1},
            {ID: 'RFF', MIN: 0, MAX: 99},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'ALI', MIN: 0, MAX: 1},
            {ID: 'QTY', MIN: 0, MAX: 99},
            {ID: 'TSR', MIN: 0, MAX: 99},
            {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'GEI', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'PYT', MIN: 0, MAX: 99},
            {ID: 'LOC', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'FTX', MIN: 0, MAX: 9},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'GEI', MIN: 0, MAX: 99},
            {ID: 'ALI', MIN: 0, MAX: 99},
            {ID: 'ERP', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'ELU', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 9},
            {ID: 'LOC', MIN: 0, MAX: 99},
            {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
        ]},
        {ID: 'TAX', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'ALI', MIN: 0, MAX: 99},
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'QTY', MIN: 0, MAX: 99},
            {ID: 'PAI', MIN: 0, MAX: 9, LEVEL: [
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GIR', MIN: 0, MAX: 9, LEVEL: [
                    {ID: 'LOC', MIN: 0, MAX: 99},
                    {ID: 'VLI', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                        {ID: 'IFD', MIN: 0, MAX: 1},
                        {ID: 'DTM', MIN: 0, MAX: 99},
                        {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'COM', MIN: 0, MAX: 99},
                        ]},
                    ]},
                ]},
            ]},
        ]},
        {ID: 'GOR', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'LOC', MIN: 0, MAX: 1},
        ]},
        {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'QTY', MIN: 0, MAX: 99},
        ]},
        {ID: 'STS', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'ELU', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'TMP', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'MEA', MIN: 0, MAX: 99},
            {ID: 'DGS', MIN: 0, MAX: 99},
        ]},
        {ID: 'TOD', MIN: 0, MAX: 1, LEVEL: [
            {ID: 'LOC', MIN: 0, MAX: 99},
            {ID: 'GEI', MIN: 0, MAX: 99},
        ]},
        {ID: 'CNI', MIN: 0, MAX: 9999, LEVEL: [
            {ID: 'RFF', MIN: 0, MAX: 99},
            {ID: 'GEI', MIN: 0, MAX: 99},
            {ID: 'STS', MIN: 0, MAX: 99},
            {ID: 'CNT', MIN: 0, MAX: 1},
            {ID: 'QTY', MIN: 0, MAX: 99},
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'IFD', MIN: 0, MAX: 99},
            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 9, LEVEL: [
                    {ID: 'MOA', MIN: 0, MAX: 99},
                    {ID: 'PYT', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 99},
                {ID: 'TSR', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'FTX', MIN: 0, MAX: 9},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 99},
                {ID: 'ERP', MIN: 0, MAX: 9, LEVEL: [
                    {ID: 'ELU', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 9},
                {ID: 'LOC', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
            ]},
            {ID: 'PAC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'PCI', MIN: 0, MAX: 99},
                {ID: 'FTX', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'DIM', MIN: 0, MAX: 99},
                {ID: 'MEA', MIN: 0, MAX: 99},
            ]},
            {ID: 'TMP', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'MEA', MIN: 0, MAX: 99},
                {ID: 'DGS', MIN: 0, MAX: 99},
            ]},
            {ID: 'EQD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 1},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'SEL', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'SEQ', MIN: 1, MAX: 1},
                ]},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
            ]},
            {ID: 'TDT', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'QTY', MIN: 0, MAX: 99},
                {ID: 'MEA', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'POC', MIN: 0, MAX: 99},
                {ID: 'DIM', MIN: 0, MAX: 99},
                {ID: 'FTX', MIN: 0, MAX: 99},
                {ID: 'GDS', MIN: 0, MAX: 99},
                {ID: 'STS', MIN: 0, MAX: 1},
                {ID: 'GPO', MIN: 0, MAX: 1},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'NAT', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'EQD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'SEQ', MIN: 1, MAX: 1},
                    {ID: 'QTY', MIN: 0, MAX: 1},
                    {ID: 'GEI', MIN: 0, MAX: 99},
                    {ID: 'SEL', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'SEQ', MIN: 1, MAX: 1},
                    ]},
                    {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
                        {ID: 'IFD', MIN: 0, MAX: 1},
                        {ID: 'DTM', MIN: 0, MAX: 99},
                        {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'COM', MIN: 0, MAX: 99},
                        ]},
                    ]},
                ]},
            ]},
        ]},
        {ID: 'LIN', MIN: 0, MAX: 9999, LEVEL: [
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'IFD', MIN: 0, MAX: 99},
            {ID: 'STS', MIN: 0, MAX: 9},
            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
            {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 99},
                {ID: 'TSR', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'FTX', MIN: 0, MAX: 9},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 99},
                {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'ELU', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 9},
                {ID: 'LOC', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
            ]},
            {ID: 'MEA', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'QTY', MIN: 0, MAX: 99},
            ]},
            {ID: 'PAC', MIN: 0, MAX: 999, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
                {ID: 'PCI', MIN: 0, MAX: 99},
                {ID: 'FTX', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'DIM', MIN: 0, MAX: 99},
                {ID: 'MEA', MIN: 0, MAX: 99},
            ]},
            {ID: 'ARD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'PCD', MIN: 0, MAX: 99},
            ]},
            {ID: 'GID', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IMD', MIN: 0, MAX: 99},
                {ID: 'APP', MIN: 0, MAX: 99},
                {ID: 'FTX', MIN: 0, MAX: 99},
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GIR', MIN: 0, MAX: 99},
                {ID: 'GIN', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'PRC', MIN: 0, MAX: 99},
                {ID: 'MEA', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'CDI', MIN: 0, MAX: 99},
                {ID: 'PGI', MIN: 0, MAX: 99},
                {ID: 'TCC', MIN: 0, MAX: 99},
                {ID: 'CNT', MIN: 0, MAX: 99},
                {ID: 'IFD', MIN: 0, MAX: 99},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'SEQ', MIN: 1, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'RFF', MIN: 0, MAX: 99},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'MOA', MIN: 0, MAX: 99},
                    {ID: 'ALI', MIN: 0, MAX: 1},
                    {ID: 'QTY', MIN: 0, MAX: 99},
                    {ID: 'TSR', MIN: 0, MAX: 99},
                    {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'IFD', MIN: 0, MAX: 1},
                        {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'COM', MIN: 0, MAX: 99},
                        ]},
                    ]},
                    {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'FTX', MIN: 0, MAX: 9},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'GEI', MIN: 0, MAX: 99},
                    {ID: 'ALI', MIN: 0, MAX: 99},
                    {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'ELU', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'PAC', MIN: 0, MAX: 999, LEVEL: [
                    {ID: 'PCI', MIN: 0, MAX: 99},
                    {ID: 'FTX', MIN: 0, MAX: 99},
                    {ID: 'GEI', MIN: 0, MAX: 99},
                    {ID: 'DIM', MIN: 0, MAX: 99},
                    {ID: 'MEA', MIN: 0, MAX: 99},
                ]},
                {ID: 'COD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'QTY', MIN: 0, MAX: 99},
                    {ID: 'PCD', MIN: 0, MAX: 99},
                    {ID: 'GEI', MIN: 0, MAX: 99},
                ]},
                {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 9},
                    {ID: 'LOC', MIN: 0, MAX: 99},
                    {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                        {ID: 'IFD', MIN: 0, MAX: 1},
                        {ID: 'DTM', MIN: 0, MAX: 99},
                        {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'COM', MIN: 0, MAX: 99},
                        ]},
                    ]},
                ]},
                {ID: 'TAX', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'ALI', MIN: 0, MAX: 99},
                    {ID: 'MOA', MIN: 0, MAX: 99},
                    {ID: 'QTY', MIN: 0, MAX: 99},
                    {ID: 'PAI', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'RFF', MIN: 0, MAX: 99},
                        {ID: 'MOA', MIN: 0, MAX: 99},
                        {ID: 'DTM', MIN: 0, MAX: 99},
                        {ID: 'GIR', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'LOC', MIN: 0, MAX: 99},
                            {ID: 'VLI', MIN: 0, MAX: 1},
                            {ID: 'DTM', MIN: 0, MAX: 99},
                            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                                {ID: 'IFD', MIN: 0, MAX: 1},
                                {ID: 'DTM', MIN: 0, MAX: 99},
                                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                                    {ID: 'COM', MIN: 0, MAX: 99},
                                ]},
                            ]},
                        ]},
                    ]},
                ]},
                {ID: 'DLI', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'MOA', MIN: 0, MAX: 99},
                ]},
                {ID: 'STS', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'ELU', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'TMP', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'MEA', MIN: 0, MAX: 99},
                    {ID: 'DGS', MIN: 0, MAX: 99},
                ]},
                {ID: 'EQD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'SEQ', MIN: 1, MAX: 1},
                ]},
            ]},
        ]},
    ]},
    {ID: 'HYN', MIN: 1, MAX: 1},
    {ID: 'CNI', MIN: 0, MAX: 9999, LEVEL: [
        {ID: 'RFF', MIN: 0, MAX: 99},
        {ID: 'GEI', MIN: 0, MAX: 99},
        {ID: 'STS', MIN: 0, MAX: 99},
        {ID: 'MEA', MIN: 0, MAX: 1},
        {ID: 'QTY', MIN: 0, MAX: 99},
        {ID: 'MOA', MIN: 0, MAX: 99},
        {ID: 'IFD', MIN: 0, MAX: 99},
        {ID: 'HAN', MIN: 0, MAX: 1},
        {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'IFD', MIN: 0, MAX: 1},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'COM', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 99},
        ]},
        {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'RFF', MIN: 0, MAX: 99},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'ALI', MIN: 0, MAX: 1},
            {ID: 'QTY', MIN: 0, MAX: 99},
            {ID: 'TSR', MIN: 0, MAX: 99},
            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'FTX', MIN: 0, MAX: 9},
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'GEI', MIN: 0, MAX: 99},
            {ID: 'ALI', MIN: 0, MAX: 99},
            {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'ELU', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 9},
            {ID: 'LOC', MIN: 0, MAX: 99},
            {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
        ]},
        {ID: 'TOD', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'RTE', MIN: 0, MAX: 1},
            {ID: 'MOA', MIN: 0, MAX: 1},
        ]},
        {ID: 'PAC', MIN: 0, MAX: 9, LEVEL: [
            {ID: 'PCI', MIN: 0, MAX: 99},
            {ID: 'FTX', MIN: 0, MAX: 99},
            {ID: 'GEI', MIN: 0, MAX: 99},
            {ID: 'DIM', MIN: 0, MAX: 99},
            {ID: 'MEA', MIN: 0, MAX: 99},
        ]},
        {ID: 'TMP', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'MEA', MIN: 0, MAX: 99},
            {ID: 'DGS', MIN: 0, MAX: 99},
        ]},
        {ID: 'RSL', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'QTY', MIN: 0, MAX: 99},
            {ID: 'DTM', MIN: 0, MAX: 99},
        ]},
        {ID: 'GOR', MIN: 0, MAX: 1, LEVEL: [
            {ID: 'LOC', MIN: 0, MAX: 1},
        ]},
        {ID: 'EQD', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'SEQ', MIN: 1, MAX: 1},
            {ID: 'QTY', MIN: 0, MAX: 1},
            {ID: 'GEI', MIN: 0, MAX: 99},
            {ID: 'SEL', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
            ]},
            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
        ]},
        {ID: 'TDT', MIN: 0, MAX: 99, LEVEL: [
            {ID: 'DTM', MIN: 0, MAX: 99},
            {ID: 'RFF', MIN: 0, MAX: 99},
            {ID: 'QTY', MIN: 0, MAX: 99},
            {ID: 'MEA', MIN: 0, MAX: 99},
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'POC', MIN: 0, MAX: 99},
            {ID: 'DIM', MIN: 0, MAX: 99},
            {ID: 'FTX', MIN: 0, MAX: 99},
            {ID: 'GDS', MIN: 0, MAX: 99},
            {ID: 'STS', MIN: 0, MAX: 1},
            {ID: 'GPO', MIN: 0, MAX: 1},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'NAT', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'LOC', MIN: 0, MAX: 99},
                {ID: 'EMP', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
                {ID: 'ADR', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'EMP', MIN: 0, MAX: 1},
                ]},
            ]},
            {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 99},
                {ID: 'TSR', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
                {ID: 'AJT', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'ELU', MIN: 0, MAX: 99},
                    ]},
                ]},
            ]},
            {ID: 'EQD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 1},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'SEL', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'SEQ', MIN: 1, MAX: 1},
                ]},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
            ]},
        ]},
        {ID: 'SEQ', MIN: 0, MAX: 9999, LEVEL: [
            {ID: 'GEI', MIN: 0, MAX: 99},
            {ID: 'STS', MIN: 0, MAX: 99},
            {ID: 'RFF', MIN: 0, MAX: 99},
            {ID: 'IFD', MIN: 0, MAX: 99},
            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
            {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 99},
                {ID: 'TSR', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
                {ID: 'AJT', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'ELU', MIN: 0, MAX: 99},
                    ]},
                ]},
            ]},
            {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'FTX', MIN: 0, MAX: 9},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 99},
                {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'ELU', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'INP', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 9},
                {ID: 'LOC', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
            ]},
            {ID: 'MEA', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'QTY', MIN: 0, MAX: 99},
            ]},
            {ID: 'PAC', MIN: 0, MAX: 999, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
                {ID: 'PCI', MIN: 0, MAX: 99},
                {ID: 'FTX', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'DIM', MIN: 0, MAX: 99},
                {ID: 'MEA', MIN: 0, MAX: 99},
            ]},
            {ID: 'TMP', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'MEA', MIN: 0, MAX: 99},
                {ID: 'DGS', MIN: 0, MAX: 99},
            ]},
            {ID: 'EQD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 1},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'SEL', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'SEQ', MIN: 1, MAX: 1},
                ]},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'GID', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IMD', MIN: 0, MAX: 99},
                {ID: 'APP', MIN: 0, MAX: 99},
                {ID: 'FTX', MIN: 0, MAX: 99},
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GIR', MIN: 0, MAX: 99},
                {ID: 'GIN', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'PRC', MIN: 0, MAX: 99},
                {ID: 'MEA', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'CDI', MIN: 0, MAX: 99},
                {ID: 'PGI', MIN: 0, MAX: 99},
                {ID: 'TCC', MIN: 0, MAX: 99},
                {ID: 'IFD', MIN: 0, MAX: 99},
                {ID: 'CNT', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
                {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'RFF', MIN: 0, MAX: 99},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'MOA', MIN: 0, MAX: 99},
                    {ID: 'ALI', MIN: 0, MAX: 1},
                    {ID: 'QTY', MIN: 0, MAX: 99},
                    {ID: 'TSR', MIN: 0, MAX: 99},
                    {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'IFD', MIN: 0, MAX: 1},
                        {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'COM', MIN: 0, MAX: 99},
                        ]},
                    ]},
                    {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'DTM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'FTX', MIN: 0, MAX: 9},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'GEI', MIN: 0, MAX: 99},
                    {ID: 'ALI', MIN: 0, MAX: 99},
                    {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'ELU', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'PAC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'PCI', MIN: 0, MAX: 99},
                    {ID: 'FTX', MIN: 0, MAX: 99},
                    {ID: 'GEI', MIN: 0, MAX: 99},
                    {ID: 'DIM', MIN: 0, MAX: 99},
                    {ID: 'MEA', MIN: 0, MAX: 99},
                ]},
                {ID: 'COD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'QTY', MIN: 0, MAX: 99},
                    {ID: 'PCD', MIN: 0, MAX: 99},
                    {ID: 'GEI', MIN: 0, MAX: 99},
                ]},
                {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 9},
                    {ID: 'LOC', MIN: 0, MAX: 99},
                    {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                        {ID: 'IFD', MIN: 0, MAX: 1},
                        {ID: 'DTM', MIN: 0, MAX: 99},
                        {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'COM', MIN: 0, MAX: 99},
                        ]},
                    ]},
                ]},
                {ID: 'TAX', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'ALI', MIN: 0, MAX: 99},
                    {ID: 'MOA', MIN: 0, MAX: 99},
                    {ID: 'QTY', MIN: 0, MAX: 99},
                    {ID: 'PAI', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'RFF', MIN: 0, MAX: 99},
                        {ID: 'MOA', MIN: 0, MAX: 99},
                        {ID: 'DTM', MIN: 0, MAX: 99},
                        {ID: 'GIR', MIN: 0, MAX: 99, LEVEL: [
                            {ID: 'LOC', MIN: 0, MAX: 99},
                            {ID: 'VLI', MIN: 0, MAX: 1},
                            {ID: 'DTM', MIN: 0, MAX: 99},
                            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                                {ID: 'IFD', MIN: 0, MAX: 1},
                                {ID: 'DTM', MIN: 0, MAX: 99},
                                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                                    {ID: 'COM', MIN: 0, MAX: 99},
                                ]},
                            ]},
                        ]},
                    ]},
                ]},
                {ID: 'DLI', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'MOA', MIN: 0, MAX: 99},
                ]},
                {ID: 'STS', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'ELU', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'TMP', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'MEA', MIN: 0, MAX: 99},
                    {ID: 'DGS', MIN: 0, MAX: 99},
                ]},
            ]},
        ]},
        {ID: 'LIN', MIN: 0, MAX: 9999, LEVEL: [
            {ID: 'MOA', MIN: 0, MAX: 99},
            {ID: 'IFD', MIN: 0, MAX: 99},
            {ID: 'STS', MIN: 0, MAX: 99},
            {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'IFD', MIN: 0, MAX: 1},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'COM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 99},
            ]},
            {ID: 'DOC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'RFF', MIN: 0, MAX: 99},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 1},
                {ID: 'QTY', MIN: 0, MAX: 99},
                {ID: 'TSR', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
                {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'DTM', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'RCS', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'FTX', MIN: 0, MAX: 9},
                {ID: 'DTM', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'ALI', MIN: 0, MAX: 99},
                {ID: 'ERP', MIN: 0, MAX: 99, LEVEL: [
                    {ID: 'ELU', MIN: 0, MAX: 99},
                ]},
            ]},
            {ID: 'INP', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'DTM', MIN: 0, MAX: 9},
                {ID: 'LOC', MIN: 0, MAX: 99},
                {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [
                    {ID: 'IFD', MIN: 0, MAX: 1},
                    {ID: 'DTM', MIN: 0, MAX: 99},
                    {ID: 'CTA', MIN: 0, MAX: 99, LEVEL: [
                        {ID: 'COM', MIN: 0, MAX: 99},
                    ]},
                ]},
            ]},
            {ID: 'MEA', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'QTY', MIN: 0, MAX: 99},
            ]},
            {ID: 'PAC', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'SEQ', MIN: 1, MAX: 1},
                {ID: 'PCI', MIN: 0, MAX: 99},
                {ID: 'FTX', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'DIM', MIN: 0, MAX: 99},
                {ID: 'MEA', MIN: 0, MAX: 99},
            ]},
            {ID: 'ARD', MIN: 0, MAX: 99, LEVEL: [
                {ID: 'MOA', MIN: 0, MAX: 99},
                {ID: 'GEI', MIN: 0, MAX: 99},
                {ID: 'PCD', MIN: 0, MAX: 99},
            ]},
        ]},
    ]},
    {ID: 'UNS', MIN: 1, MAX: 1},
    {ID: 'AUT', MIN: 0, MAX: 1},
    {ID: 'CNT', MIN: 0, MAX: 9},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
